[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_swap = "GWF4At68GQQT6rnKFkGEeAuT8TxbYMbgVHpfpYkTvyuq"
[programs.devnet]
solana_swap = "GWF4At68GQQT6rnKFkGEeAuT8TxbYMbgVHpfpYkTvyuq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
my-custom-script = "echo 'Hello world!'"